main:
  - identifier: blog
    name: Блог
    weight: 2
    params:
      icon:
        vendor: fas
        name: blog

  - name: Поддержка
    identifier: support
    weight: 100
    url: https://github.com/goroedge
    params:
      header: The HB support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Документация
    url: docs
    weight: 3
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentation.

  - name: GitHub
    parent: support
    url: https://github.com/goroedge
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Написать в telegram
    parent: support
    url: https://t.me/ra_igor
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  
  - name: Mastodon
    parent: support
    url: https://techhub.social/@goroedge
    weight: 16
    params:
      icon:
        vendor: simple
        name: mastodon
      description: Follow us on Mastodon to get latest updates.
